<<<<<<< HEAD
import type { Viewport, Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
=======
import '@/styles/globals.css';
>>>>>>> upstream/main

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Frontend Coda Comigo",
  description: "Aplicação com componentes reutilizáveis e PWA.",
  manifest: "/manifest.json", 
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
  },
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> upstream/main
};

export const viewport: Viewport = {
  themeColor: "#e8059cff",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
<<<<<<< HEAD
    <html lang="pt-BR">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#eab5cc" />
      </head>
      <body>{children}</body>
=======
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} dark antialiased`}>{children}</body>
>>>>>>> upstream/main
    </html>
  )
}