'use client'

import { Navbar } from '@/components/ds/navbar';
import { TooltipProvider } from '@/components/ui/tooltip';
import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} dark antialiased`}>
        <TooltipProvider>
          {children}
          <Navbar active={`/${pathname}`} />
        </TooltipProvider>
      </body>
    </html>
  );
}
